### ISSUE TITLE
Conversions between different multimap types

### ISSUE THREAD

**Issue by chris-martin** [zliu41/multi-containers#1]
Hey, thank you for publishing this library!

Is there a recommended way to convert, e.g. a `SetMultimap` to a `Multimap`? Do you think maybe a `Data.Multimap.Conversions` module or something like that might be warranted?

**Comment by zliu41** [comment]
@chris-martin Thanks for the suggestion! There are the `toMap` and `fromMap` functions that can be used to do the conversion via `Map`, but not only is it verbose but the size needs to be re-computed. So adding some conversion functions is a very good idea. Will do soon.

**Comment by zliu41** [comment]
The conversion functions are added in f7c8269cb216ca8f2b169658da4e5a88c04789ca. Thanks again for the suggestion!
